ElSecretary/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElSecretary.Models;
using Microsoft.AspNet.Identity;
using ImageResizer;

namespace ElSecretary.Controllers
{
    public class CatalogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {

            if (User.Identity.GetUserName() == "admin@els.com")
            {
                List<ItemCatalog> cropTextToDescriptAdmin = db.ItemCatalogs.ToList();
                foreach (var item in cropTextToDescriptAdmin)
                {
                    if (item.Description.Length > 50)
                        item.Description = item.Description.Substring(0, 50) + "...";
                }
                return View("IndexAdmin", cropTextToDescriptAdmin);
                
            }
            else if (User.Identity.GetUserName() != "")
            {
                List<ItemCatalog> cropTextToDescriptUser = db.ItemCatalogs.ToList();
                foreach (var item in cropTextToDescriptUser)
                {
                    if (item.Description.Length > 50)
                        item.Description = item.Description.Substring(0, 50) + "...";
                }
                return View("IndexRegistred", cropTextToDescriptUser);
            }

            List<ItemCatalog> cropTextToDescriptGuest = db.ItemCatalogs.ToList();
            foreach (var item in cropTextToDescriptGuest)
            {
                if (item.Description.Length > 50)
                    item.Description = item.Description.Substring(0, 50) + "...";
            }
            return View(cropTextToDescriptGuest);
        }

        // GET: Catalog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCatalog itemCatalog = db.ItemCatalogs.Find(id);
            if (itemCatalog == null)
            {
                return HttpNotFound();
            }
            return View(itemCatalog);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemCatalog itemCatalog, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        uploadImage.InputStream.Seek(0, System.IO.SeekOrigin.Begin);

                        ImageBuilder.Current.Build(
                            new ImageJob(uploadImage.InputStream, ms, new Instructions("maxwidth=200&maxheight=200"),
                                false,
                                false));
                        itemCatalog.Image = ms.ToArray();
                    }
                }
                db.ItemCatalogs.Add(itemCatalog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(itemCatalog);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCatalog itemCatalog = db.ItemCatalogs.Find(id);
            if (itemCatalog == null)
            {
                return HttpNotFound();
            }
            return View(itemCatalog);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemCatalog itemCatalog, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        uploadImage.InputStream.Seek(0, System.IO.SeekOrigin.Begin);

                        ImageBuilder.Current.Build(
                            new ImageJob(uploadImage.InputStream, ms, new Instructions("maxwidth=280&maxheight=280"),
                                false,
                                false));
                        itemCatalog.Image = ms.ToArray();
                    }
                }
                db.Entry(itemCatalog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemCatalog);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCatalog itemCatalog = db.ItemCatalogs.Find(id);
            if (itemCatalog == null)
            {
                return HttpNotFound();
            }
            return View(itemCatalog);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemCatalog itemCatalog = db.ItemCatalogs.Find(id);
            db.ItemCatalogs.Remove(itemCatalog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElSecretary/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElSecretary.Models;
using Microsoft.AspNet.Identity;

namespace ElSecretary.Controllers
{
    public class ForumController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Forum
        public ActionResult Index(int? id)
        {
            List<ForumMessage> forumMessages = db.ForumMessages.ToList();
            List<ForumMessage> forumMessagesOut = new List<ForumMessage>();
            foreach (var item in forumMessages)
            {
                if (item.ItemCatalogId == id)
                {
                    forumMessagesOut.Add(item);
                }
            }
            ViewBag.isAdmin = User.Identity.GetUserName();
            ViewBag.idDevice = id;

            return View(forumMessagesOut);
        }

        [Authorize]
        [HttpPost]
        public ActionResult NewMessage(ForumMessage forumModel, int? idDevice)
        {

            forumModel.Owner = User.Identity.GetUserName();
            forumModel.DateTime = DateTime.Now;
            forumModel.ItemCatalogId = idDevice;

            db.ForumMessages.Add(forumModel);
            db.SaveChanges();

            Response.Redirect(Request.UrlReferrer.ToString());
            return null;
        }

        [Authorize(Users = "admin@els.com")]
        public ActionResult DeleteMessage(int? id)
        {
            ForumMessage message = db.ForumMessages.Find(id);
            if (message == null)
                return HttpNotFound();

            db.ForumMessages.Remove(message);
            db.SaveChanges();
            
            Response.Redirect(Request.UrlReferrer.ToString());

            return null;
        }
    }
}

ElSecretary/Views/Catalog/Create.cshtml
@model ElSecretary.Models.ItemCatalog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ItemCatalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", cols = 45, rows = 10 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <span class="btn btn-default btn-file">
                        Browse <input type="file" name="uploadImage" />
                    </span>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AverageCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AverageCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AverageCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raiting, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raiting, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raiting, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElSecretary/Views/Catalog/Delete.cshtml
@model ElSecretary.Models.ItemCatalog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemCatalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                @Html.Raw("<img style='width:350px; height:350px;' src=\"data:image/jpeg;base64,"
                      + Convert.ToBase64String(Model.Image) + "\" />")
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AverageCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AverageCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raiting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raiting)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ElSecretary/Views/Catalog/Details.cshtml
@using ElSecretary.Controllers
@model ElSecretary.Models.ItemCatalog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ItemCatalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>

            @if (Model.Image != null)
            {
                @Html.Raw("<img style='width:280px; height:280px;' src=\"data:image/jpeg;base64,"
                      + Convert.ToBase64String(Model.Image) + "\" />")
            }

        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>

        </dt>



        <dt>
            @Html.DisplayNameFor(model => model.AverageCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AverageCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raiting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raiting)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

@Html.Action("Index", "Forum");

ElSecretary/Views/Catalog/Edit.cshtml
@model ElSecretary.Models.ItemCatalog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ItemCatalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea rows="10" cols="45" name="Description" class="form-control">@Model.Description</textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <span class="btn btn-default btn-file">
                        Browse <input type="file" name="uploadImage" />
                    </span>
                </div>
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AverageCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AverageCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AverageCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raiting, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raiting, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raiting, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElSecretary/Views/Catalog/Index.cshtml
@model IEnumerable<ElSecretary.Models.ItemCatalog>

@{
    ViewBag.Title = "Catalog";
}

<h2>Catalog</h2>

<p>

</p>
<table class="table">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raiting)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @if (item.Image != null)
                {
                    @Html.Raw("<img style='width:80px; height:80px;' src=\"data:image/jpeg;base64,"
                              + Convert.ToBase64String(item.Image) + "\" />")
                }

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.AverageCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raiting)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>

ElSecretary/Views/Catalog/IndexAdmin.cshtml
@model IEnumerable<ElSecretary.Models.ItemCatalog>

@{
    ViewBag.Title = "Catalog";
}

<h2>Catalog</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raiting)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (item.Image != null)
                {
                    @Html.Raw("<img style='width:80px; height:80px;' src=\"data:image/jpeg;base64,"
                      + Convert.ToBase64String(item.Image) + "\" />")
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raiting)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

ElSecretary/Views/Catalog/IndexRegistred.cshtml
@model IEnumerable<ElSecretary.Models.ItemCatalog>

@{
    ViewBag.Title = "Catalog";
}

<h2>Catalog</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raiting)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (item.Image != null)
                {
                    @Html.Raw("<img style='width:80px; height:80px;' src=\"data:image/jpeg;base64,"
                      + Convert.ToBase64String(item.Image) + "\" />")
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raiting)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>